version: '3'
services:

  reverse-proxy:
    image: traefik:v2.1
    networks:
      - internal
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  database:
    image: postgres:12-alpine
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: swordfish
      POSTGRES_DB: promotion
    volumes:
      - ./config/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - 5432:5432

  promotion:
    build:
       context: ./promotion
       dockerfile: Dockerfile
    command: serve grpc
    environment:
      - DATABASE_URL=postgres://postgres:swordfish@database:5432/promotion?sslmode=disable
      - TEST_DATABASE_URL=
      - BLACK_FRIDAY_DATE="2020-11-25"
      - USER_BIRTHDAY_PERCENTAGE=5
      - MAX_DISCOUNT_PERCENTAGE=10
      - BLACK_FRIDAY_PERCENTAGE=10
    networks:
      - internal
    depends_on:
      - database

  product-grpc:
    build:
       context: ./product
       dockerfile: Dockerfile
    command: serve grpc
    networks:
      - internal
    environment:
      - LISTENADDRESS=:13666
      - DSN=postgres://postgres:swordfish@database:5432/product?sslmode=disable
      - TRACERENDPOINT=http://jaeger:14268
      - METRIClISTENADDRESS=:8888
    ports:
      - 13666
      - 8888
    depends_on:
      - database
      - promotion

  product-http:
    build:
       context: ./product
       dockerfile: Dockerfile
    command: serve http
    networks:
      - internal
    environment:
      - CONNECTADDRESS=product-grpc:13666
      - LISTENADDRESS=:80
      - TRACERENDPOINT=http://jaeger:14268
    ports:
      - 80
    depends_on:
      - product-grpc
    labels:
      - "traefik.http.routers.product.rule=Host(`product.d.wiliam.dev`)"

  load:
    build:
       context: ./load
       dockerfile: Dockerfile
    command: --host 'http://product-http' --no-web -c 10 -t 1h
    networks:
      - internal
    environment:
      - DATABASE_URL=
      - TEST_DATABASE_URL=
      - BLACK_FRIDAY_DATE="2020-11-25"
      - USER_BIRTHDAY_PERCENTAGE=5
      - MAX_DISCOUNT_PERCENTAGE=10
      - BLACK_FRIDAY_PERCENTAGE=10
    depends_on:
      - product-grpc
      - product-http
      - promotion

  jaeger:
    image: jaegertracing/all-in-one:1.8
    networks:
      - internal
    ports:
      - 16686:16686
      - 14268

  prometheus:
    image: prom/prometheus
    networks:
      - internal
    command: ["--config.file=/etc/prometheus/config.yaml"]
    volumes:
      - ./config/prometheus/:/etc/prometheus/
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    networks:
      - internal
    ports:
      - 3000:3000
    depends_on:
      - prometheus

networks:
  internal:
  default:
    external:
      name: bridge
