  global:
    scrape_interval:     15s
    evaluation_interval: 15s
    external_labels:
        monitor: 'marketplace'

  scrape_configs:

    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
           - targets: ['prometheus:9090']


    - job_name: 'collector'
      scrape_interval: 5s
      static_configs:
           - targets: ['collector:8888']
